### ISSUE TITLE
Mixamo YBot and licensing

### ISSUE THREAD

**Issue by SilverWolf32** [armory3d/armory_tutorials#1]
Everything I can find on Mixamo's content licensing seems to point to it being usable in commercial projects, but [**not** open source](https://forums.adobe.com/thread/1992542).

[playground/license.md](playground/license.md) says the Playground tutorial uses Mixamo's YBot, which would seem to make the entire repository not open source. But [the main license](LICENSE.md) indicates that it's zlib-licensed.

Could someone please clarify this?

**Comment by luboslenco** [comment]
Distribution of raw Mixamo files is not allowed - I was originally under impression those are defined as the actual files obtained from the Mixamo website (in fuse [terms](https://wwwimages2.adobe.com/content/dam/acom/en/legal/servicetou/Fuse_Additional_Terms_en_US_20180605.pdf) - BVH, FBX, OBJ or Collada formats), preventing the competing service to rip/resell the models.

Nonetheless the linked forum thread seems to make the definition of raw files much more broad. The best solution is probably to replace the YBot, looking into it.. Thanks for bringing this up!

**Comment by luboslenco** [comment]
Replaced the ybot, thanks for issue report!
